### ISSUE TITLE
Plugin stuck in Loading state

### ISSUE THREAD

**Issue by Soumil4561** [1Mack/CS2-Whitelist#1]
Release: 1.0.2
CSS Version: 1.0.239
when using command css_plugins list, it shows the plugin is stuck in loading state and does not change even after waiting. 
<img width="458" alt="whitelist_loading" src="https://github.com/1Mack/CS2-Whitelist/assets/95604494/9ac75a66-8c54-4df1-946e-4df64f478b4a">

**Comment by 1Mack** [comment]
@Soumil4561 Did u set up the config file right?

**Comment by Atarikloi23** [comment]
I am also having this issue, cfg file is set up properly.

**Comment by 1Mack** [comment]
@Atarikloi23 look at your console... there is probably an error message when loading the plugin
